version: "3.7"
services:

  luvio:
    build: .
    ports:
      - "8080:80"
    environment: 
      - MONGODB_URL=mongodb://%2Ftmp%2Fluvio%2Fmongod.sock/luvio
    depends_on: 
      - mongo
    volumes:
      - type: bind
        source: /tmp/luvio
        target: /tmp/luvio

  mongo:
    image: mongo:3
    command: ["mongod", "--bind_ip", "/tmp/luvio/mongod.sock"]
    volumes:
      - type: volume
        source: mongo
        target: /data/db
      - type: bind
        source: /tmp/luvio
        target: /tmp/luvio

volumes:
  mongo: