version: "3.7"
services:

  tipper:
    build: .
    ports:
      - "8080:80"
    environment: 
      - MONGODB_URL=mongodb://mongo/tipper
    depends_on: 
      - mongo

  mongo:
    image: mongo:3
    hostname: mongo
    volumes:
      - mongo:/data/db

volumes:
  mongo: